<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skipped="0" tests="4" time="0.049"><testcase classname="test_calc" file="test_calc.py" line="4" name="test_add[1-2-3]" time="0.001"></testcase><testcase classname="test_calc" file="test_calc.py" line="4" name="test_add[0.3333333333333333-0.3333333333333333-0.6666666666666666]" time="0.001"></testcase><testcase classname="test_calc" file="test_calc.py" line="4" name="test_add[-1-1-0]" time="0.001"><failure message="assert 2 == 0
  -2
  +0">a = -1, b = 1, result = 0

    @pytest.mark.parametrize(&apos;a, b, result&apos;, [
        [1, 2, 3],
        [1/3, 1/3, 2/3],
        [-1, 1, 0],
        [0.5, 0.5, 1]
    ])
    def test_add(a, b, result):
&gt;       assert calc.add(a, b) == result
E       assert 2 == 0
E         -2
E         +0

test_calc.py:12: AssertionError</failure></testcase><testcase classname="test_calc" file="test_calc.py" line="4" name="test_add[0.5-0.5-1]" time="0.001"></testcase></testsuite>